### ISSUE TITLE
git_merge is not callable using argument types

### ISSUE THREAD

**Issue by BlackEdder** [s-ludwig/libgit2#1]
I'm trying to implement pulling from D, but cannot get the merge step to work. I keep getting:

Error: function deimos.git2.merge.git_merge (git_merge_result*\* out_, git_repository\* repo, const(git_merge_head)*\* their_heads, ulong their_heads_len, const(git_merge_opts)\* opts) is not callable using argument types (git_merge_result**, git_repository*, git_merge_head**, ulong, git_merge_opts*)

which I cannot seem to solve. Except for the const the function signatures look the same to me.

The relevant piece of code:

```
    git_object* fetch_head;
    enforce( git_revparse_single(&fetch_head, repo, "FETCH_HEAD") == 0 );
    git_oid *fetch_head_id = cast(git_oid *)fetch_head; 
    git_merge_head *merge_fetch_head;
    enforce( git_merge_head_from_fetchhead(&merge_fetch_head, repo, "master",
            "origin", fetch_head_id) == 0 );

    git_merge_result *result;
    git_merge_opts *merge_opts;
    size_t length = 1;
    git_merge(&result, repo, &merge_fetch_head, length, merge_opts);
```

This fails to compile on the last line.

**Comment by s-ludwig** [comment]
The issue is that `git_merge_head**` doesn't implicitly convert to `const(git_merge_head)**`*, so you'd first need to store a `const(git_merge_head)*`:

```
const(git_merge_head)* their_head = merge_fetch_head;
git_merge(&result, repo, &their_head, 1, merge_opts);
```

\* explanation:

```
int* someptr;
const(int)** ptrtoptr = &someptr; // not allowed, because:
*ptrtoptr = new immutable int(13);
*someptr = 42; // changing the immutable int!
```

**Comment by BlackEdder** [comment]
That makes sense, thanks! I wrongly assumed that mutable object could always be passed to function that require a const.

It now compiles fine (the actual merge is not working as I hoped it would, but at least I got it to compile. Back to the docs for me :) )

**Comment by s-ludwig** [comment]
BTW, are you aware of [dlibgit](http://code.dlang.org/packages/dlibgit)? It's still missing the merge module unfortunately, but apart from that it makes working with libgit much more bearable (the learning curve is still steep, of course).

**Comment by BlackEdder** [comment]
I am aware of that project (I started looking at that), but there is very little documentation for that. All examples on how to do (higher level) things where based on the c api, so I found it easier to just use that directly.

**Comment by s-ludwig** [comment]
The D API more or less directly corresponds to the C API, apart from the naming convention and that  most things are organized as classes/methods instead of free functions (an exception is the authentication module, which is going to be partially rewritten).

But it easily reduces the amount of written code by two thirds or more, because all the boilerplate code isn't needed. And once you have a grip on the library, it lets you concentrate on the problem at hand, rather than constantly worrying about conversions, error handling and resource cleanup.
